### ISSUE TITLE
Meta-annotate @Story with @ExtendWith(StoryExtension.class)

### ISSUE THREAD

**Issue by sbrannen** [udaychandra/bdd#2]
If `@Story` is always declared at the class level and cannot be used without the `StoryExtension`, it is then a best practice to meta-annotate `@Story` with `@ExtendWith(StoryExtension.class)` to simplify configuration for your users.

**Comment by udaychandra** [comment]
Cool, that makes sense. Thanks for pointing it out. Updated "@Story"

**Comment by sbrannen** [comment]
👍
